# Generated by Django 3.0.11 on 2021-01-11 08:09

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(10, 'Новый'), (20, 'В обработке'), (30, 'Выполнен'), (40, 'Отменён')], default=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.Service', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=14, verbose_name='Стоимость'),
        ),
    ]
